# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
# Use the HA Python base images (Alpine) - Python and pip are pre-installed
build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base-python:3.12-alpine3.21"
  amd64: "ghcr.io/home-assistant/amd64-base-python:3.12-alpine3.21"
  armv7: "ghcr.io/home-assistant/armv7-base-python:3.12-alpine3.21"
  armhf: "ghcr.io/home-assistant/armhf-base-python:3.12-alpine3.21"
