# Base images for each architecture (Supervisor uses this when building the add-on)
build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base:3.19"
  amd64: "ghcr.io/home-assistant/amd64-base:3.19"
  armv7: "ghcr.io/home-assistant/armv7-base:3.19"
  armhf: "ghcr.io/home-assistant/armhf-base:3.19"
