site_name: Concord232 API Docs
site_url: https://example.com/
theme:
  name: material
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: true
nav:
  - Home: index.md
  - API Reference: api.md
