name: CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install uv
        run: pip install uv

      - name: Set up uv venv and install dependencies
        run: |
          uv venv .venv
          source .venv/bin/activate
          uv pip install -e .
          uv pip install pytest

      - name: Run tests
        run: |
          source .venv/bin/activate
          pytest
